import Head from 'next/head';
import { Fragment } from 'react';
import { Article } from './../../models/article';
import ArticleDetail from './../../components/articles/ArticleDetail';
import DUMMY_ARTICLES from './../api/dummy_articles';
import { GetStaticProps, GetStaticPaths  } from 'next';

const ArticleDetailPage: React.FC<{ article: Article }> = (props) => {
	return (
		<Fragment>
			<Head>
				<title>{props.article.title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ArticleDetail article={props.article} />
		</Fragment>
	);
};

export default ArticleDetailPage;

export const getStaticPaths: GetStaticPaths = async () => {
	return {
		fallback: 'blocking',
		paths: DUMMY_ARTICLES.map((art) => ({
			params: {
				articleId: art.slug
			}
		}))
	};
}

export const getStaticProps: GetStaticProps = async ({ params }) => {
	const articleId = params?.articleId;

	return {
		props: {
			article: DUMMY_ARTICLES.find((art) => art.slug === articleId)
		}
	};
};
