import Head from 'next/head';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Arnaud Martin</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<p>
				Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque, sint repudiandae qui, architecto
				perspiciatis rerum odit doloremque molestias nulla necessitatibus inventore nisi fuga distinctio
				obcaecati quos consequatur dolor, facilis aperiam!
			</p>
		</div>
	);
}
